/**
 * Token validation script.
 *
 * Re-measures the Examples-page token claim for every gallery scenario:
 *
 *   1. `.aui`        — the exact source shown on the page (gallery.ts).
 *   2. Generated     — the deterministic React the compiler emits from the
 *                      same parsed AST (compileReact.ts).
 *   3. Hand-written  — the realistic React implementation of the same screen
 *                      authored for validation (handwritten.ts).
 *
 * All three are counted with the real GPT-4/GPT-3.5 BPE tokenizer
 * (`gpt-tokenizer`), the same tokenizer OpenAI's API uses.
 *
 * Usage (from apps/www):
 *   npm run validate:tokens          # measure, print, and write token-report.json
 *   npm run validate:tokens --check  # verify the committed report matches current
 *
 * The script exits non-zero if any scenario is missing its hand-written
 * counterpart, if `.aui` is not strictly smaller than hand-written React, or
 * (in --check mode) if the committed report is stale.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parse } from '@codedia/parser';
import { GALLERY } from '../src/lib/gallery.ts';
import { HANDWRITTEN } from '../src/lib/handwritten.ts';
import { compileReact } from '@codedia/parser';
import { countTokens } from '../src/lib/tokens.ts';

const REPORT_PATH = join(dirname(fileURLToPath(import.meta.url)), '..', 'token-report.json');
const CHECK_MODE = process.argv.includes('--check');

interface ScenarioTokens {
  id: string;
  title: string;
  aui: number;
  generated: number;
  handwritten: number;
}

function measure(): ScenarioTokens[] {
  const rows: ScenarioTokens[] = [];
  const failures: string[] = [];

  for (const scenario of GALLERY) {
    const handwritten = HANDWRITTEN[scenario.id];
    if (handwritten === undefined) {
      failures.push(`Missing hand-written React for scenario "${scenario.id}" in src/lib/handwritten.ts`);
      continue;
    }

    const aui = countTokens(scenario.auiCode);
    const generated = countTokens(compileReact(parse(scenario.auiCode)));
    const handwrittenTokens = countTokens(handwritten);

    if (!(aui < handwrittenTokens)) {
      failures.push(`Scenario "${scenario.id}": .aui (${aui}) is not smaller than hand-written React (${handwrittenTokens})`);
    }
    if (!(generated <= handwrittenTokens)) {
      failures.push(`Scenario "${scenario.id}": generated React (${generated}) exceeds hand-written React (${handwrittenTokens})`);
    }

    rows.push({ id: scenario.id, title: scenario.title, aui, generated, handwritten: handwrittenTokens });
  }

  if (failures.length > 0) {
    console.error('\nValidation failed:');
    for (const f of failures) console.error('  ✗ ' + f);
    process.exit(1);
  }
  return rows;
}

function pad(s: string, width: number): string {
  return s.length >= width ? s : s + ' '.repeat(width - s.length);
}

function print(rows: ScenarioTokens[]): void {
  console.log('\nToken comparison — GPT-4/GPT-3.5 BPE tokenizer (gpt-tokenizer)');
  console.log('='.repeat(110));
  console.log(pad('Scenario', 30) + pad('.aui', 10) + pad('Generated', 12) + pad('Hand-written', 14) + pad('Saved vs hand-written', 24) + 'React is larger');
  console.log('-'.repeat(110));
  let auiTotal = 0;
  let genTotal = 0;
  let handTotal = 0;
  for (const r of rows) {
    auiTotal += r.aui;
    genTotal += r.generated;
    handTotal += r.handwritten;
    const saved = r.handwritten - r.aui;
    console.log(
      pad(r.title.slice(0, 28), 30) +
        pad(String(r.aui), 10) +
        pad(String(r.generated), 12) +
        pad(String(r.handwritten), 14) +
        pad(String(saved), 24) +
        (r.handwritten / r.aui).toFixed(1) + '×',
    );
  }
  console.log('-'.repeat(110));
  console.log(
    pad('TOTAL', 30) +
      pad(String(auiTotal), 10) +
      pad(String(genTotal), 12) +
      pad(String(handTotal), 14) +
      pad(String(handTotal - auiTotal), 24) +
      (handTotal / auiTotal).toFixed(1) + '×',
  );
  console.log();
  console.log(`Saved across all scenarios: ${(handTotal - auiTotal).toLocaleString('en-US')} tokens ` +
    `(${(1 - auiTotal / handTotal) * 100}% fewer than hand-written React).`);
  console.log(`Generated React is ${genTotal} tokens — the tool's output is already smaller than hand-written.`);
}

function writeReport(rows: ScenarioTokens[]): void {
  const totals = rows.reduce(
    (acc, r) => ({ aui: acc.aui + r.aui, generated: acc.generated + r.generated, handwritten: acc.handwritten + r.handwritten }),
    { aui: 0, generated: 0, handwritten: 0 },
  );
  const report = {
    tokenizer: 'gpt-tokenizer · GPT-4/GPT-3.5 BPE (cl100k_base)',
    note: 'Generated by scripts/validate-tokens.ts — run `npm run validate:tokens` to refresh. Do not edit by hand.',
    scenarios: rows.map(({ id, title, aui, generated, handwritten }) => ({ id, title, aui, generated, handwritten })),
    totals,
  };
  writeFileSync(REPORT_PATH, JSON.stringify(report, null, 2) + '\n');
  console.log(`\nWrote ${REPORT_PATH}`);
}

function check(rows: ScenarioTokens[]): void {
  if (!existsSync(REPORT_PATH)) {
    console.error(`No committed report at ${REPORT_PATH} — run without --check first.`);
    process.exit(1);
  }
  const committed = JSON.parse(readFileSync(REPORT_PATH, 'utf8')) as {
    scenarios: { id: string; aui: number; generated: number; handwritten: number }[];
  };
  const byId = new Map(committed.scenarios.map((s) => [s.id, s]));
  const diffs: string[] = [];
  for (const r of rows) {
    const c = byId.get(r.id);
    if (!c) {
      diffs.push(`Scenario "${r.id}" missing from committed report`);
    } else if (c.aui !== r.aui || c.generated !== r.generated || c.handwritten !== r.handwritten) {
      diffs.push(
        `Scenario "${r.id}" drifted: committed (aui ${c.aui}, generated ${c.generated}, handwritten ${c.handwritten}) ` +
          `≠ current (aui ${r.aui}, generated ${r.generated}, handwritten ${r.handwritten})`,
      );
    }
  }
  for (const s of committed.scenarios) {
    if (!GALLERY.some((g) => g.id === s.id)) diffs.push(`Committed scenario "${s.id}" no longer exists`);
  }
  if (diffs.length > 0) {
    console.error('\nReport is stale — re-run `npm run validate:tokens`:');
    for (const d of diffs) console.error('  ✗ ' + d);
    process.exit(1);
  }
  console.log(`\n✓ token-report.json is current (${rows.length} scenarios match).`);
}

const rows = measure();
print(rows);
if (CHECK_MODE) {
  check(rows);
} else {
  writeReport(rows);
}
